### ISSUE TITLE
Nav bar on small screens don't collapse correctly

### ISSUE THREAD

**Issue by TobySuch** [TobySuch/Shifter#151]
On small screens, the nav bar collapses to a hamburger menu. When the button is pressend, the button containing the users email is shown. That button then needs to be clicked to show the navigation options.

Instead, I think the hamburger menu should just be the standard option. The email should maybe be displayed in the dropdown menu? 

Perhaps the entire nav bar needs a revisit (again), some buttons (like My Files) should probably be available straight away, especially on larger screens.

**Comment by OsafAliSayed** [comment]
hi, shall i work on this issue?

**Comment by TobySuch** [comment]
@OsafAliSayed Sure! 

Should be an easy enough change in css. On small screens it should show the hamburger menu and the dropdown should take the full page width, and on larger screens it should show the email address and have a small dropdown menu.
