### ISSUE TITLE
Mock-Up and Design improvements

### ISSUE THREAD

**Issue by sudoer-zero** [TobySuch/Shifter#21]
Check it out: [Shifter Mock-Up](https://www.figma.com/file/1ujvnOdXyl2cEKsrcsR6XX/Shifter?node-id=0%3A1)
_Any changes would be very good (there is always a room for improvement)_

**Comment by TobySuch** [comment]
Hi @sudoer-zero thanks for mocking this up! I appreciate the effort here. I like the overall design but I do have a couple of ideas:

- Text for the login buttons seem to be a bit small compared to the large images in the main page.
- The file upload form doesn't have a title of some sort. 
- The forms seem to be missing a "submit" button.

I'm not too sure how I feel about those large images on the right of the forms. They will need to hide themselves on mobile and smaller screens and I think the screen space could be better used. I would love to replace the file upload field with something like [DropzoneJS](https://www.dropzone.dev/js/) which would probably work best without it.

Overall though really impressed! Need to have another pass with the CSS right now anyway as I've been working on #12 and thr current design breaks when users have many files to list.

**Comment by sudoer-zero** [comment]
Hello, @TobySuch thanks for the feedback.

- button's text is now relatively larger compared to the other text.
- All titles were added properly.
- Upload/Login button added.
- Mobile mockups were created.
- Large icons were removed totally.

Now the design is much simpler.
I think the CSS code will put the design into a perspective.
I don't know, what do you think?

Check the updated version: [Shifter Mock-Up](https://www.figma.com/file/1ujvnOdXyl2cEKsrcsR6XX/Shifter?node-id=0%3A1)

**Comment by TobySuch** [comment]
Definitely like the new design! There are a couple more page we need to think about, the "View My Files" page (#12). There is a short mockup in the `add-my-files-page` for the files list and then I'm envisoning some sort of files detail page. Not sure if this is needed or whether we can keep all the information displayed in the table view. We can worry about that a bit later though. Thanks for the awesome work!

I'll leave this ticket open for tracking the CSS overhaul. Happy for you to take point on it if you would like but I can also work on this too when I get some time back.

**Comment by sudoer-zero** [comment]
For the "View My Files" page we can use iframe to embed the HTML code for the objects without affecting the rest of the page (scrollable). However, for the files detail page, we will do as you stated in #4. For the time being, I think we stick to the traditional navbar.

I will work on the CSS code for the login page for now and then move to the rest.

**Comment by TobySuch** [comment]
Cool I'm gonna have a crack at putting in a better file uploader and might touch some CSS up as I do it.

**Comment by TobySuch** [comment]
Closed by automation by mistake - not finished yet

**Comment by sudoer-zero** [comment]
The upload file page is not responsive.

**Comment by TobySuch** [comment]
@sudoer-zero are you still having this issue? It is working fine for me now.

**Comment by sudoer-zero** [comment]
I pull the recent code and works.
