### ISSUE TITLE
Anyone can download files.

### ISSUE THREAD

**Issue by TobySuch** [TobySuch/Shifter#4]
Anyone who has access to a files unique link can download the file when they visit the URL.

A landing page will show with data about the file (Name, uploader, size etc.) The download will then start automatically.

Once the download starts automatically, a download will be recorded in the database to count it.

If someone accesses a link to a file that has expired or does not exist, then it will 404.

**Comment by sudoer-zero** [comment]
I would like to work on this.

**Comment by TobySuch** [comment]
Need to do some more reading but need to be careful about how the file downloads are served.

It is not enough to just serve them from the media folder as a file may be marked as expired before it is deleted and therefore should not be served, even if someone has the link.

Should be able to use something like Nginx's `X-Accel-Redirect` header to protect it.
