### ISSUE TITLE
File owners should be able to expire their files early

### ISSUE THREAD

**Issue by TobySuch** [TobySuch/Shifter#42]
Users should be able to go to the file details page and press a button to delete the file before the expiry datetime, preventing the files from being downloaded.

To implement this, we only need to set the expiry datetime to the current datetime to prevent anyone from downloading it, and the cronjob will pick it up on the next run through.

**Comment by sudoer-zero** [comment]
What if we delete the file entirely?

**Comment by TobySuch** [comment]
We can it's just slightly more complicated. Setting the expired date is a quick and easy way to get the same effect and decouples any heavy file system related action from the web UI.
