### ISSUE TITLE
Manual trigger of the cleanup cronjob

### ISSUE THREAD

**Issue by TobySuch** [TobySuch/Shifter#43]
Admin users should be able to trigger the clean up cronjob manually without having to wait for it to run. This should be done by either a button in the UI or a Django manage.py command.

Components:
- [x] Management command
- [ ] Button in settings UI

**Comment by sudoer-zero** [comment]
I should be a button.
You can run the corn job with the Django command ie: ```python manage.py crontab run job_hash```

**Comment by TobySuch** [comment]
True, although I think it may still be worth adding in a management command for it. Having to go in and find the job hash to trigger the command isn't as simple as just telling people to run `docker-compose exec web python manage.py cleanup-expired` or something like that. 

A GUI button does also make sense though. Toying with the idea of having some admin page with all the application specific settings - could be a nice home for a cleanup button too.
